[package]
name = "bundle"
version = "0.1.0"
edition = "2024"

[lib]
name = "bundle"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"
once_cell = "1.21.3"
goblin = "0.8"
